export const evevntDataCard = [


    {
        id: 1,
        eventName: "Tech Conference 2025",
        eventDescription: "A global tech conference featuring industry leaders and many more.",
        eventCategory: "Technology",
        eventStartDate: new Date("2025-06-15T09:00:00Z"),
        eventEndDate: new Date("2025-06-16T18:00:00Z"),
        eventTimeSlots: ["09:00 AM - 12:00 PM", "02:00 PM - 05:00 PM"],
        eventDaysOfWeeks: ["Monday", "Tuesday"],
        eventTotalSeats: 500,
        eventImage: "https://source.unsplash.com/400x300/?conference",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 2,
        eventName: "Art Expo 2025",
        eventDescription: "An exhibition showcasing contemporary art from around the world.",
        eventCategory: "Art",
        eventStartDate: new Date("2025-07-10T10:00:00Z"),
        eventEndDate: new Date("2025-07-12T17:00:00Z"),
        eventTimeSlots: ["10:00 AM - 01:00 PM", "03:00 PM - 06:00 PM"],
        eventDaysOfWeeks: ["Friday", "Saturday", "Sunday"],
        eventTotalSeats: 300,
        eventImage: "https://source.unsplash.com/400x300/?art",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 3,
        eventName: "Music Festival 2025",
        eventDescription: "A two-day outdoor music festival featuring top artists and many more.",
        eventCategory: "Music",
        eventStartDate: new Date("2025-08-20T14:00:00Z"),
        eventEndDate: new Date("2025-08-21T23:00:00Z"),
        eventTimeSlots: ["02:00 PM - 11:00 PM"],
        eventDaysOfWeeks: ["Saturday", "Sunday"],
        eventTotalSeats: 1000,
        eventImage: "https://source.unsplash.com/400x300/?music",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        eventName: "Startup Networking Meetup",
        eventDescription: "A networking event for entrepreneurs and investors and many more.",
        eventCategory: "Business",
        eventStartDate: new Date("2025-09-05T18:00:00Z"),
        eventEndDate: new Date("2025-09-05T21:00:00Z"),
        eventTimeSlots: ["06:00 PM - 09:00 PM"],
        eventDaysOfWeeks: ["Thursday"],
        eventTotalSeats: 150,
        eventImage: "https://source.unsplash.com/400x300/?business",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        eventName: "Startup Networking Meetup",
        eventDescription: "A networking event for entrepreneurs and investors and many more.",
        eventCategory: "Business",
        eventStartDate: new Date("2025-09-05T18:00:00Z"),
        eventEndDate: new Date("2025-09-05T21:00:00Z"),
        eventTimeSlots: ["06:00 PM - 09:00 PM"],
        eventDaysOfWeeks: ["Thursday"],
        eventTotalSeats: 150,
        eventImage: "https://source.unsplash.com/400x300/?business",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        eventName: "Startup Networking Meetup",
        eventDescription: "A networking event for entrepreneurs and investors and many more.",
        eventCategory: "Business",
        eventStartDate: new Date("2025-09-05T18:00:00Z"),
        eventEndDate: new Date("2025-09-05T21:00:00Z"),
        eventTimeSlots: ["06:00 PM - 09:00 PM"],
        eventDaysOfWeeks: ["Thursday"],
        eventTotalSeats: 150,
        eventImage: "https://source.unsplash.com/400x300/?business",
        created_at: new Date(),
        updated_at: new Date(),
    }
    ,
    {
        id: 4,
        eventName: "Startup Networking Meetup",
        eventDescription: "A networking event for entrepreneurs and investors and many more.",
        eventCategory: "Business",
        eventStartDate: new Date("2025-09-05T18:00:00Z"),
        eventEndDate: new Date("2025-09-05T21:00:00Z"),
        eventTimeSlots: ["06:00 PM - 09:00 PM"],
        eventDaysOfWeeks: ["Thursday"],
        eventTotalSeats: 150,
        eventImage: "https://source.unsplash.com/400x300/?business",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        id: 4,
        eventName: "Startup Networking Meetup",
        eventDescription: "A networking event for entrepreneurs and investors and many more.",
        eventCategory: "Business",
        eventStartDate: new Date("2025-09-05T18:00:00Z"),
        eventEndDate: new Date("2025-09-05T21:00:00Z"),
        eventTimeSlots: ["06:00 PM - 09:00 PM"],
        eventDaysOfWeeks: ["Thursday"],
        eventTotalSeats: 150,
        eventImage: "https://source.unsplash.com/400x300/?business",
        created_at: new Date(),
        updated_at: new Date(),
    }
];


